### ISSUE TITLE
Need a little help with BtRigidBody plz

### ISSUE THREAD

**Issue by Sondro** [armory3d/haxebullet#19]
Trying to get this to compile on cpp (JS is fine) and need a base var. I don't know what to plug in for the BtStridingMeshInterface. 

I get the error: "cannot construct a btStridingMeshInterface, no constructor in IDL" because it's an interface. 

Thinking about sticking some kind of tri or collision shape in there but not really sure which.

       public var fallRigidBody:BtRigidBody = BtRigidBody.create(BtRigidBodyConstructionInfo.create
	(
		0, 
		BtDefaultMotionState.create(BtTransform.create(), BtTransform.create()), 
		BtBvhTriangleMeshShape.create(BtStridingMeshInterface.create(), false, false), 
		BtVector3.create(0, 0, 0)
	));

**Comment by luboslenco** [comment]
Yup, this should help:
https://github.com/armory3d/armory/blob/master/Sources/armory/trait/physics/bullet/RigidBody.hx#L128

**Comment by Sondro** [comment]
Hey thanks for the above, I don't know how I missed that.

I'm still getting 'error C2512: 'btRigidBody': no appropriate default constructor available' (which is a repeated problem with other files).

Not quite sure what I'm missing, I thought this would fix that.
