### ISSUE TITLE
'btRigidBody': no appropriate default constructor available

### ISSUE THREAD

**Issue by Sondro** [armory3d/haxebullet#20]
Hi, in the cpp build I'm still getting "error C2512: 'btRigidBody': no appropriate default constructor available" (which is a repeated problem with other files, ie btDiscreteDynamicsWorld).

I tried this type of construction, but not really sure what to do at this point : https://github.com/armory3d/haxebullet/issues/19

**Comment by Sondro** [comment]
So after talking to the guys at #kha apparently I need btRigidBody:btRigidBodyPointer = create()... OR remove the type and have it auto assigned, ie btRigidBody = create()...;

cpp still not quite compiling because of some render issue, but I'll leave this open for a little while in case there is something else you want to add.

**Comment by luboslenco** [comment]
Sorry I did not get to this sooner.

Robert hooked up a Bullet example recently:
https://github.com/Kha-Samples/BulletTest

Cpp compilation fix by removing the type:
https://github.com/Kha-Samples/BulletTest/commit/fd6df9fde8a80eb7d55af348c5ff305e019e16f2

Or using the predefined `BtThingyPointer` typedefs, on cpp those ends up as `cpp.Star<>` types:
https://github.com/armory3d/haxebullet/blob/master/Sources/haxebullet/Bullet.hx#L1836

**Comment by Sondro** [comment]
Thanks, much appreciated.

Do you know whether the BtPointers would be more or less performant?

**Comment by luboslenco** [comment]
No perf difference - BtPointer typedefs allow to write the same code for both js/hxcpp (as on cpp it wraps the types into `cpp.Star<>`).
