### ISSUE TITLE
What Do We Need To Autogenerate Javascript Bindings?

### ISSUE THREAD

**Issue by zicklag** [armory3d/haxebullet#25]
I was looking around because I needed some extra bindings that I found were not in Bt.hx but were in the WebIDL and I found that the Javascript bindings were not generated automatically yet.

https://github.com/armory3d/haxebullet/blob/a5a8649ff8dfc6d82d1147abbbb121ad30b85514/Sources/bullet/Bt.hx#L11

If it is worth your time to explain, I might be able to do the work to get that done. Before I started on anything I just wanted to make sure you haven't already figured out what we need to do. If it isn't worth the time right now, no problem, I don't care either way, I'll just add the extra bindings that I need to Bt.hx for now.

**Comment by luboslenco** [comment]
Help on this would be amazing! The macro at:

https://github.com/armory3d/haxebullet/blob/a5a8649ff8dfc6d82d1147abbbb121ad30b85514/Sources/bullet/Bt.hx#L7

is also supposed to work for JS.

- We should probably compile our own "ammo.js" using [webidl](https://github.com/ncannasse/webidl) and emscripten, so the generated bindings match.
- Calling the `webidl.Module.build` macro above every time seemed to pro-long the build times. Perhaps it would be better to somehow output the generated bindings into `.hx` file and reuse that.

Still a novice on this myself but was amazed how it worked so far. We can basically drop-in any C/C++ lib just by writing the `.idl` file.

**Comment by zicklag** [comment]
OK awesome. If I get the time, I'll look into it. :+1:

**Comment by zicklag** [comment]
I just got a custom Emscripten build of bullet using the Haxe Webidl library. It looks like it works! I've already been able to get a Haxe extern file from it so that we should be able to cache the externs and avoid generating them every build. Using the WebIDL gives exactly the same bindings for JS and HL which is awesome and takes out all of the `#if js #else #end` stuff from `PhysicsWorld` and friends.

Now I'm going to try to integrate the binder into Khamake/Koremake so that you can use it for any Kha project just by adding a WebIDL file and some statements to you Khamake.js file. :tada: This is going to be so awesome if it works.

**Comment by luboslenco** [comment]
😍😍😍

**Comment by zicklag** [comment]
It works!!! Last night I got an end to end build that successfully utilized the entire workflow! I've still got a little bit of cleanup and slight re-organization, but I should be done today or tomorrow! I'll have PRs for Kha, Khamake, haxebullet, and Armory.

**Comment by luboslenco** [comment]
Sounds awesome, can't wait!

**Comment by zicklag** [comment]
I ran into some issues, but I'm getting close to finishing. I have gotten most of it working, but then ran into an [issue](https://github.com/emscripten-core/emscripten/issues/8042) when enabling MODULARIZE for the Emscripten build. I'm also not 100% sure I've figured out how to make sure that JS libs are loaded before the game starts.

Right now I'm working on figuring out if there is an alternative to using `eval()` to load the JS lib. Maybe the [`Function`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/eval#Do_not_ever_use_eval!), which is supposed to be a better alternative to `eval`.

**Comment by zicklag** [comment]
@luboslenco and @RobDangerous I've opened the following PRs for the automatic WebIDL binding system for Kha projects and for Armory's Bullet bindings:

* https://github.com/Kode/khamake/pull/187
* https://github.com/Kode/Kha/pull/986
* https://github.com/armory3d/armory/pull/1159
* https://github.com/armory3d/haxebullet/pull/27
* https://github.com/ncannasse/webidl/pull/10

There is kind of a lot changes throughout those repos so tell me if I missed anything. I'm can give more description of how it works later, but I figured I'd submit these for review.

It is looking really cool. I'm so excited about this update! :smiley: :confetti_ball:

**Comment by zicklag** [comment]
I created a Gist that documents how to use the new Khabind feature: [Khabind: Binding C++ Libraries To Kha For JS/HashLink](https://gist.github.com/zicklag/6c2828cda4e8282c850d97ac8a3a0de5).

**Comment by zicklag** [comment]
### Review Note

I included the bytecode generated by Emscripten in the PR for Haxebullet because the way that I setup the compiler cache in Khamake was that it will compile any C/C++ source file that doesn't have a corresponding bytecode file with a newer timestamp. Technically I could add some more logic to the compiler cache so that it would not compile any sources if there is already the generated JavaScript library that has a newer timestamp than all of the source files. It would just add slightly more complication to the build logic so if you don't think it is a problem I will just leave it, otherwise I have no problem making it a little smarter.

**Comment by luboslenco** [comment]
Thanks, this is big! Will have fun this weekend. 🙂 (+ doing a proper [haxerecast](https://github.com/armory3d/haxerecast) upgrade is also easier now!)

**Comment by zicklag** [comment]
Awesome. I can't wait to get some feedback on my code! :)

Also, I did manage to figure out what was causing it to run out of memory. The WebIDL [binder](https://github.com/emscripten-core/emscripten/blob/incoming/tools/webidl_binder.py) that comes with Emscripten that is used to create Ammo.js does some sort of wrapping for the C++ pointers that can garbage collect them automatically ( for classes that don't require a destructor ). The bindings that we are generating with our WebIDL binder, though, doesn't do any garbage collecting for you. This left a memory leak in `PhysicsWorld.updateContacts()`. I fixed that one, but there might be some more laying around in the different physics classes.

It looks like ncannasse/webidl does have the auto garbage collector option that should work for HashLink, which is good. It is up to you whether or not we want to use it for Bullet in Armory, but I'm also going to do my best to figure out if I can use the trick that the Emscripten WebIDL binder used to get JavaScript to garbage collect it like Ammo.js did.

**Comment by zicklag** [comment]
Linking: https://github.com/ncannasse/webidl/issues/15.

**Comment by luboslenco** [comment]
Getting more familiar with it! Is it a bad idea to have `khabind.json` contained directly in `khafile.js` library file as a 'regular' command?

**Comment by zicklag** [comment]
The reason I had it in its own file because `khafile.js` files are only processed by Khamake when you include a sub-project, and not when you just include a library like haxebullet. `korefile.js` would be another option, but that's not quite right either because those are only processed during Kore builds.

**Comment by RobDangerous** [comment]
"sub-projects" are merely more powerful libraries and I think I can persuade Lubos to add a khafile to haxebullet.

**Comment by zicklag** [comment]
In that case it should be perfectly fine. It would probably be good to make the handling less 'special' so to speak.

**Comment by zicklag** [comment]
@RobDangerous Does it make any sense to have Khamake automatically add a project if you are adding a library with a `khafile.js` in it? It seems like it would be nice just to be able to drop haxebullet in your Libraries folder to include it in a Kha project.

**Comment by RobDangerous** [comment]
No, the big difference is that loading a project is async because khafiles require that.

**Comment by zicklag** [comment]
Just pushed updates to all of the repos to use `khafile.js` instead of `khabind.json`.

**Comment by zicklag** [comment]
It looks like there actually isn't a way  to get JavaScript to auto GC the references. :slightly_frowning_face: ( see https://github.com/emscripten-core/emscripten/issues/8206#issuecomment-468031992 ) I don't know why we didn't see the out of memory exceptions with the Ammo.js version that we used to use, though. :thinking: I'm not sure if it had the heap set to growable or if it was something else, but either way it looks like we will just have to fix the memory leaks. I fixed the major ones, but there is still at least another minor one, because I had it running for an extended time period earlier and it ran out of memory again.

**Comment by luboslenco** [comment]
Growable heap should be disabled in current ammo.js build, so I guess the current one should also crash eventually? How long is extended time period? 🕐 Do all physics enabled scenes run into this? Will try to reproduce.

**Comment by zicklag** [comment]
At first it would crash within a few minutes before I pushed, https://github.com/armory3d/armory/pull/1159/commits/d43d9c45fa3be5420e7bc413e3e6a243ceac4d5c. After that the only time I've noticed a crash was with a basic rigid body sim that I had accidentally let run for a couple hours or so. Still if the Ammo.js build doesn't have a growable heap, then I can't immagine what is making it not crash if there is no way to auto GC memory. Maybe we should test reverting https://github.com/armory3d/armory/pull/1159/commits/d43d9c45fa3be5420e7bc413e3e6a243ceac4d5c to make the effect more apparent and then compare Ammo.js and our custom build. Mabye my Khabind script isn't correctly setting the heap size or something like that. This is kind of strange. :thinking: :question:

**Comment by zicklag** [comment]
Here is an example that crashes really quick. ( 400+ spheres )
[ball-example.zip](https://github.com/armory3d/haxebullet/files/2917250/ball-example.zip)

**Comment by zicklag** [comment]
Oh, I found the leak:

[RigidBody.hx:291](https://github.com/armory3d/armory/blob/66776acac72ad625e984e2c8f624ca3f2aeb9b27/Sources/armory/trait/physics/bullet/RigidBody.hx#L291)
```haxe
var p = trans.getOrigin();
var q = trans.getRotation();
var qw:bullet.Bt.QuadWord = q;
```

Just needed to delete those after use. Now the example continues working for an unknown amount of time. I'm going to try testing it with Ammo.js and see if I have the same problem.

**Comment by zicklag** [comment]
OK, I was finally able to get back to this. :slightly_smiling_face: 

Good news is, I think it is done! At least the binding part anyway. So I never figured out how Ammo.js magically avoids memory leaks, but it doesn't matter, because the memory leaks are not unique to the JavaScript build, they happen with the HashLink target as well. This means that we have to fix the memory leaks by adding the proper `delete()` calls anyway.

I went through and I found the last memory leak that occurs when doing a pure rigid body simulation ( without cloth, soft bodies, or constraints ). The simulation can run with hundreds of objects without steadily increasing in memory usage, now. There might be some more in the cloth, soft body, or constraint code still.

### Remaining Issues

I notice that some of the physics behave a bit differently than Ammo.js did with the new bindings. The behavior of Convex Hull shaped objects is sporadic and it seems like the mesh collision shape has some issues when I try to set the floor to use it ( it freezes in Krom and things go through it in HashLink ). I don't really have any experience with the Bullet API so I don't know that I will be able to fix that right now.

The good thing about it, though, is that the JavaScript build now behaves the same as the HashLink build, so any issues that we have in Krom are probably just things that we hadn't noticed were already an issue in HashLink builds.

@lubos If you could test it out that would be great. I've got a simple blend with some test objects where you can see the convex hull shape issue, and if you set the floor to use a mesh collision shape you can see the mesh shape issue as well.

[basic_test.zip](https://github.com/armory3d/haxebullet/files/3105350/basic_test.zip)

**Comment by zicklag** [comment]
**Update:** It looks like the latest changes have a problem with Haxe 4.0.0-rc that comes with Kha right now. Gives a very undescribed `Invalid_argument("index out of bounds")`. Works with 4.0.0-rc2 though. @RobDangerous are you good with updating Haxe for Kha?

**Comment by RobDangerous** [comment]
Nope, sorry, I've seen several reports about critical issues in rc2, won't update before rc3.

**Comment by luboslenco** [comment]
See https://github.com/Kode/Kha/pull/986, hoping to revisit in the future. Thanks!
