### ISSUE TITLE
[FR] Please include AllHitsRayResultCallback in haxelib

### ISSUE THREAD

**Issue by trsh** [armory3d/haxebullet#26]
We have encountered some situations where it becomes very handy for armory project.

**Comment by zicklag** [comment]
I'm working on updating the way that the Bullet classes are bound to Haxe so I'll look into exposing that when I get it working.

**Comment by trsh** [comment]
@zicklag will it be cross Platform, also HTML-JS builds?

**Comment by zicklag** [comment]
Yep, it should work for HL/C, Krom, and HTML5 builds.

**Comment by trsh** [comment]
Is see there is callback function addSingleResult, that fixates hit object. If we can expose and override that, we can create our own callbacks. Like secondHitRayResultCallback :)

**Comment by zicklag** [comment]
I wanted to do that, too. When first I tried Krom would crash, so I'm not 100% sure whether or not it is possible to extend a C++ ( compiled to JavaScript ) class in the plain JavaScript Haxe generates. I haven't done a lot of testing, so I'll have to try it again later.

**Comment by trsh** [comment]
@zicklag how far is this?

**Comment by zicklag** [comment]
I've got open PRs that are awaiting review by Lubos and Robert: https://github.com/armory3d/haxebullet/issues/25#issuecomment-462210471. As soon as that is finished ( or maybe before ) I'll add the bindings for `AllHitsRayResultCallback`. It is a big change so it will take longer to review and test so it might be just a little bit.

**Comment by luboslenco** [comment]
Link with https://github.com/armory3d/haxebullet/issues/25.
