### ISSUE TITLE
haxelib.json missing

### ISSUE THREAD

**Issue by Ohmnivore** [armory3d/haxebullet#5]
haxelib.json disappeared in this commit: https://github.com/armory3d/haxebullet/tree/bce65966e086432981fc4c17b5818229c636ad84

It was present in the previous one, as can be seen here: https://github.com/armory3d/haxebullet/tree/2b87efd5ce0b23732a90828f7fb121379c7cf494

Without a haxelib.json, lime-based projects can't find the proper classPath, and can't resolve any classes as a result. I was previously on a very old commit which still had the haxelib, so this only recently caused me trouble when I upgraded xD

**Comment by luboslenco** [comment]
Oops, it's back! :)

**Comment by Ohmnivore** [comment]
Thanks!
