### ISSUE TITLE
error C2819: type 'btRigidBody' does not have an overloaded member 'operator ->'

### ISSUE THREAD

**Issue by Ohmnivore** [armory3d/haxebullet#6]
I'm on Haxe 3.2.0 (afraid of migrating because of my the legacy openfl/lime/haxeflixel stuff I use for other projects), and I'm having some trouble building the most recent commit. I'm using hxcpp 3.3.49 (which I think is the latest on haxelib).

Here's what the compiler outputs:
```
Error: While running :cl.exe -Iinclude -IC:\HaxeToolkit\haxe\lib\haxebullet/git/Sources/../cpp/bullet -nologo /WX- /fp:precise -DHX_WINDOWS -D_USING_V120_SDK71_ -GR -Od -Zi -FdC:\Users\Anon\Desktop\HAXEDEV\BlipEngine\bin\windows\cpp\debug\obj\obj/msvc18-debug-ncxp/vc.pdb -FS -Oy- -c -EHs -GS- -arch:SSE -IC:/HaxeToolkit/haxe/lib/hxcpp/3,3,49/include -DHXCPP_DEBUG -DHXCPP_VISIT_ALLOCS -DHXCPP_CHECK_POINTER -DHXCPP_STACK_TRACE -DHXCPP_STACK_LINE -DHXCPP_API_LEVEL=321 -D_CRT_SECURE_NO_DEPRECATE -D_ALLOW_MSC_VER_MISMATCH -D_ALLOW_ITERATOR_DEBUG_LEVEL_MISMATCH -wd4996 -MT ./src/subsector/Player.cpp -FoC:/Users/Anon/Desktop/HAXEDEV/BlipEngine/bin/windows/cpp/debug/obj/obj/msvc18-debug-ncxp/025d0416_Player.obj
Player.cpp
./src/subsector/Player.cpp(153) : error C2819: type 'btRigidBody' does not have an overloaded member 'operator ->'
        C:\HaxeToolkit\haxe\lib\haxebullet\git\cpp\bullet\BulletDynamics/Dynamics/btRigidBody.h(62) : see declaration of 'btRigidBody'
        did you intend to use '.' instead?
./src/subsector/Player.cpp(153) : error C2232: '->btCollisionObject::setUserIndex' : left operand has 'class' type, use '.'
```

Here's Player.cpp(153):
```
this->phys->body->get_value()->setUserIndex((int)666);
```

And this is the original Haxe line:
```
phys.body.value.setUserIndex(666);
```

`body` is a cpp.Pointer<BtRigidBody>, so it seems that the generated code mistakes the return value of the get_value() for a pointer. Is this just a Haxe 3.2/3.3 incompatibility?

**Comment by luboslenco** [comment]
Can you try this one?
```
phys.body.ptr.setUserIndex(666);
```

Other code may require similar changes like this. Had serious trouble migrating to Haxe 3.3, I am not sure Haxe 3.2 will work for latest commits. Library now produces much cleaner C++ code though, so it should be worth it in the end.

**Comment by Ohmnivore** [comment]
`phys.body.ptr.setUserIndex(666);` works :)

Is it the new proper way to keep code cross-platform, or do you still use `.value` in 3.3 code?

**Comment by luboslenco** [comment]
Great! I also use .ptr for this one, and .value for BtVector3 and alike(things defined as cpp::Struct in Bullet.hx).

**Comment by Ohmnivore** [comment]
Ah ok i replaced the necessary `.value` occurences by `.ptr` in my code until i got no error messages. JS works just like it used to, but in cpp I can't steer my ship anymore. I'll check the bullet changelogs, something probably changed between versions.

**Comment by Ohmnivore** [comment]
Hmm it's odd, it seems like RigidBodies have acquired infinite rotational inertia, it only happens on cpp with bullet 2.83.7.
