### ISSUE TITLE
Crash on android

### ISSUE THREAD

**Issue by DmitriyKarpov** [armory3d/haxebullet#8]
On Android 4.4 application crashes on dynamicsWorld.stepSimulation(1/60) call. I also tested It on Android 5.0, linux, html5 and it works fine. There are no any errors in logcat and I don't know how to capture this error. Can somebody suggest solution? I tested on 2 smartphones with Android 4.4.2 and 4.4.3, both crashes

**Comment by luboslenco** [comment]
Hm, weird that Android 5.0 is fine but 4.4 is not. Does emulator also crash? Maybe trying a different [bullet](https://github.com/bulletphysics/bullet3) versions would have some effect, replacing the bundled one at https://github.com/armory3d/haxebullet/tree/master/cpp/bullet.

**Comment by DmitriyKarpov** [comment]
I've updated bullet version to 2.87. Now it works fine. Thanks for your help

**Comment by luboslenco** [comment]
Nice! I will also update the included bullet version as well.

**Comment by luboslenco** [comment]
Updated cpp bullet to 2.87.
https://github.com/armory3d/haxebullet/commit/f2735a249330cdb23323e52d8768659f69dd0f7e
